import {
  defaultProfile,
  defaultSettings,
  type Snapshot,
  type Application,
  verticals,
} from "./types";
const now = "2026-09-16T08:00:00.000Z";
const names = [
  "Atlas Capital (démo)",
  "Orion Partners (démo)",
  "Northbridge Credit (démo)",
  "Studio Groupe (démo)",
  "Horizon Equities (démo)",
  "Meridian Advisory (démo)",
];
export function demoSnapshot(): Snapshot {
  return {
    demo: true,
    email: "Mode démonstration",
    connections: { google: false, openai: false, search: false, cron: false },
    profile: { ...defaultProfile, name: "Candidat de démonstration" },
    settings: defaultSettings,
    contacts: [
      {
        id: "demo-contact",
        createdAt: now,
        updatedAt: now,
        applicationId: "demo-1",
        company: names[1],
        name: "Camille Exemple (fictif)",
        role: "Associate M&A",
        type: "Équipe",
        email: "",
        emailStatus: "NOT_FOUND",
        linkedin: "",
        source: "",
        alumniSkema: false,
        relevance: "Exemple de contact d’équipe pour découvrir la fiche.",
        primary: true,
      },
    ],
    documents: [
      {
        id: "demo-document",
        createdAt: now,
        updatedAt: now,
        applicationId: "demo-1",
        type: "Email",
        filename: "Email_Orion_DEMONSTRATION_v1",
        text: "Candidature Analyste M&A - exemple fictif\n\nBonjour,\n\nCe texte de démonstration illustre la présentation d’un document versionné. Il ne constitue pas une candidature réelle et ne contient aucune preuve de votre parcours.\n\nBien cordialement,",
        version: 1,
        usedForApplication: false,
        quality: "Démonstration fictive, aucun envoi possible",
      },
    ],
    interactions: [
      {
        id: "demo-interaction",
        createdAt: now,
        updatedAt: now,
        applicationId: "demo-3",
        type: "Exemple de timeline",
        summary:
          "Un entretien fictif est prévu pour illustrer le suivi. Aucune invitation réelle.",
      },
    ],
    logs: [],
    applications: names.map(
      (company, i) =>
        ({
          id: "demo-" + i,
          company,
          jobTitle: [
            "Analyste investissement",
            "Analyste M&A",
            "Analyste dette privée",
            "Analyste Corporate Development",
            "Equity Research Analyst",
            "Analyste M&A",
          ][i],
          vertical: [
            verticals[0],
            verticals[3],
            verticals[2],
            verticals[4],
            verticals[1],
            verticals[3],
          ][i],
          priority: i < 3 ? "A" : "B",
          careerPriority: "À évaluer",
          location: "Paris",
          contractType: i % 2 ? "CDI" : "Stage",
          startDate: "2027-01",
          reference: "",
          status: [
            "À analyser",
            "À préparer",
            "Envoyée",
            "En process",
            "Inbox",
            "Refus",
          ][i],
          stage: i === 3 ? "Entretien 1" : "Candidature",
          officialUrl: "",
          description:
            "Offre fictive réservée à la démonstration. Aucune candidature réelle.",
          publicationDate: "",
          deadline: "",
          nextAction: [
            "Analyser l’offre",
            "Préparer la candidature",
            "Vérifier la réponse",
            "Préparer l’entretien",
            "Qualifier l’offre",
            "Clôturer",
          ][i],
          nextActionDate: "2026-09-16",
          applicationDate: i === 2 ? "2026-09-08" : "",
          lastInteraction: "",
          notes: "",
          isWatch: i === 4,
          ignored: false,
          sources: [],
          createdAt: now,
          updatedAt: now,
        }) as Application,
    ),
  };
}
