import { Application, Contact } from './types';

const now = new Date().toISOString();
export const demoApplications: Application[] = [
  { id:'newco', company:'NewCo Corporate Finance', jobTitle:'Analyst M&A', vertical:['M&A / IB'], priority:'A', careerPriority:'B', status:'Envoyée', stage:'Candidature', fitScore:8.5, location:'Paris', contractType:'CDI', channel:'Email', applicationDate:'2026-09-16', nextAction:'Relancer si aucun retour', nextActionDate:'2026-09-23', strengths:['Exécution M&A directe','Valorisation','Contacts dirigeants'], gaps:['Disponibilité janvier 2027 vs ASAP'], cvVersion:'CV FR actuel', coverLetterReady:true, emailReady:true, linkedinReady:false, formReady:false, createdAt:now, updatedAt:now },
  { id:'sg-ma', company:'Société Générale', jobTitle:'M&A Analyst Intern — Large Cap', reference:'26000JV6', vertical:['M&A / IB'], priority:'A', careerPriority:'A', status:'Prête à envoyer', stage:'Candidature', fitScore:9, location:'La Défense', contractType:'Stage', officialUrl:'https://careers.societegenerale.com/', publicationDate:'2026-09-15', startDate:'2027-01-04', nextAction:'Soumettre la candidature officielle', nextActionDate:'2026-09-16', strengths:['Expérience M&A directe','DCF / comparables','Process sell-side'], gaps:['Large-cap non démontré','Convention de stage à confirmer'], cvVersion:'CV FR actuel', coverLetterReady:true, emailReady:true, linkedinReady:true, formReady:false, createdAt:now, updatedAt:now },
  { id:'bpi-tmt', company:'Bpifrance', jobTitle:'Analyste Private Equity Large Cap TMT', vertical:['Private Equity'], priority:'A', careerPriority:'A', status:'Prête à envoyer', stage:'Candidature', fitScore:8.5, location:'Paris', contractType:'Stage', startDate:'2027-01-04', nextAction:'Soumettre la candidature officielle', nextActionDate:'2026-09-16', strengths:['Valorisation','DD / analyse financière','Intérêt tech démontré'], gaps:['Aucune expérience PE professionnelle directe','Convention de stage à confirmer'], cvVersion:'CV FR actuel', coverLetterReady:true, emailReady:false, linkedinReady:false, formReady:false, createdAt:now, updatedAt:now },
  { id:'saviu', company:'Saviu', jobTitle:'Investment Analyst Intern', vertical:['Private Equity','Venture Capital'], priority:'A', careerPriority:'A', status:'À préparer', stage:'Candidature', fitScore:8.5, location:'Paris', contractType:'Stage', nextAction:'Préparer dossier et angle alumni', nextActionDate:'2026-09-17', strengths:['Analyse financière','Entrepreneuriat','M&A transférable'], gaps:['Pas d’expérience VC/PE directe'], cvVersion:'CV EN recommandé', coverLetterReady:false, emailReady:false, linkedinReady:false, formReady:false, createdAt:now, updatedAt:now },
  { id:'societex', company:'Societex Corporate Finance', jobTitle:'Stage Analyste M&A', vertical:['M&A / IB'], priority:'B', careerPriority:'B', status:'Envoyée', stage:'Candidature', fitScore:9, location:'Paris', contractType:'Stage', applicationDate:'2026-09-16', nextAction:'Relancer si nécessaire', nextActionDate:'2026-09-23', strengths:['Fit opérationnel immédiat','Valorisation','Process transactionnel'], gaps:['Incrément de carrière plus limité après Triactis'], cvVersion:'CV FR actuel', coverLetterReady:true, emailReady:true, linkedinReady:false, formReady:false, createdAt:now, updatedAt:now },
  { id:'venture-search', company:'Venture Search', jobTitle:'Debt Advisory Associate', vertical:['Private Credit'], priority:'C', careerPriority:'C', status:'Clôturée', stage:'Candidature', fitScore:4, location:'Paris', contractType:'CDI', nextAction:'Aucune', strengths:['Analyse financière transférable'], gaps:['Rôle trop senior','Credit underwriting non démontré'], createdAt:now, updatedAt:now }
];

export const demoContacts: Contact[] = [
  { id:'gregory-lhorset', company:'Société Générale', name:"Grégory L'Horset", role:'M&A Analyst Intern — Large Cap Generalist', type:'Analyst / Associate', linkedin:'https://fr.linkedin.com/in/gregory-l-horset', email:'gregorylhorset@gmail.com', emailStatus:'Public vérifié', alumniSkema:false, relevance:'Réseau', notes:'Message réseau déjà envoyé.' },
  { id:'helene-montagnon', company:'Societex Corporate Finance', name:'Hélène Montagnon', role:'Office Manager', type:'Recruteur', email:'helene.montagnon@societex.com', emailStatus:'Public vérifié', alumniSkema:false, relevance:'Principale' },
  { id:'leith-ferjani', company:'Saviu', name:'Leith Ferjani', role:'Investment team', type:'Alumni', linkedin:'https://fr.linkedin.com/in/leith-ferjani/fr', emailStatus:'Non trouvé', alumniSkema:true, relevance:'Réseau', notes:'Alumni SKEMA ayant repartagé une offre de stage.' }
];
